# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mover.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(430, 283)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_process = QtWidgets.QPushButton(self.centralwidget)
        self.btn_process.setGeometry(QtCore.QRect(170, 210, 89, 25))
        self.btn_process.setObjectName("btn_process")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(150, 10, 133, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(11, 50, 411, 27))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.txt_origin = QtWidgets.QLineEdit(self.widget)
        self.txt_origin.setObjectName("txt_origin")
        self.horizontalLayout_2.addWidget(self.txt_origin)
        self.btn_orig_find = QtWidgets.QPushButton(self.widget)
        self.btn_orig_find.setObjectName("btn_orig_find")
        self.horizontalLayout_2.addWidget(self.btn_orig_find)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(10, 90, 411, 27))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.txt_destination = QtWidgets.QLineEdit(self.widget1)
        self.txt_destination.setObjectName("txt_destination")
        self.horizontalLayout.addWidget(self.txt_destination)
        self.btn_dest_find = QtWidgets.QPushButton(self.widget1)
        self.btn_dest_find.setObjectName("btn_dest_find")
        self.horizontalLayout.addWidget(self.btn_dest_find)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(10, 130, 411, 27))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.txt_prefix = QtWidgets.QLineEdit(self.widget2)
        self.txt_prefix.setObjectName("txt_prefix")
        self.horizontalLayout_3.addWidget(self.txt_prefix)
        self.label_4 = QtWidgets.QLabel(self.widget2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.txt_suffix = QtWidgets.QLineEdit(self.widget2)
        self.txt_suffix.setObjectName("txt_suffix")
        self.horizontalLayout_3.addWidget(self.txt_suffix)
        self.widget3 = QtWidgets.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(10, 170, 411, 25))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.chk_text = QtWidgets.QCheckBox(self.widget3)
        self.chk_text.setObjectName("chk_text")
        self.horizontalLayout_4.addWidget(self.chk_text)
        self.chk_audio = QtWidgets.QCheckBox(self.widget3)
        self.chk_audio.setObjectName("chk_audio")
        self.horizontalLayout_4.addWidget(self.chk_audio)
        self.chk_video = QtWidgets.QCheckBox(self.widget3)
        self.chk_video.setObjectName("chk_video")
        self.horizontalLayout_4.addWidget(self.chk_video)
        self.chk_image = QtWidgets.QCheckBox(self.widget3)
        self.chk_image.setObjectName("chk_image")
        self.horizontalLayout_4.addWidget(self.chk_image)
        self.chk_app = QtWidgets.QCheckBox(self.widget3)
        self.chk_app.setObjectName("chk_app")
        self.horizontalLayout_4.addWidget(self.chk_app)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 430, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_process.setText(_translate("MainWindow", "Procesar"))
        self.label_5.setText(_translate("MainWindow", "Mover Archivos"))
        self.label.setText(_translate("MainWindow", "Origen"))
        self.btn_orig_find.setText(_translate("MainWindow", "Buscar"))
        self.label_2.setText(_translate("MainWindow", "Destino"))
        self.btn_dest_find.setText(_translate("MainWindow", "Buscar"))
        self.label_3.setText(_translate("MainWindow", "Prefijo"))
        self.label_4.setText(_translate("MainWindow", "Sufijo"))
        self.chk_text.setText(_translate("MainWindow", "Texto"))
        self.chk_audio.setText(_translate("MainWindow", "Audio"))
        self.chk_video.setText(_translate("MainWindow", "Video"))
        self.chk_image.setText(_translate("MainWindow", "Imagen"))
        self.chk_app.setText(_translate("MainWindow", "Aplicación"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

